# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gurobipy
        pip install unittest-xml-reporting
    - name: Install CyLP
      run: |
        sudo apt-get install -y git pkg-config coinor-libcbc-dev coinor-libosi-dev coinor-libcoinutils-dev coinor-libcgl-dev
        export COIN_INSTALL_DIR=/usr/
        pip install --pre cylp
    - name: Run unit tests
      run: |
        cd src
        python -m xmlrunner discover -s ../tests/unit -o ../tests/junit-reports
    - name: Run integration tests
      run: |
        cd src
        python -m xmlrunner discover -s ../tests/integration -o ../tests/junit-reports
    - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: tests/junit-reports/*.xml    # Path to test results
          reporter: jest-junit        #

